# Generated by Django 6.0 on 2025-12-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='bio_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='full_name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='full_name_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_en',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_ru',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='director',
            name='bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='bio_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='full_name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='full_name_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_name_ru',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre_en',
            field=models.ManyToManyField(null=True, to='movie_app.genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre_ru',
            field=models.ManyToManyField(null=True, to='movie_app.genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_name_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='slogan_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='movie',
            name='slogan_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='movievideo',
            name='video_name_en',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='movievideo',
            name='video_name_ru',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
