# Generated by Django 6.0 on 2025-12-27 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_alter_genre_category_alter_movie_actor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actorimage',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_images', to='movie_app.actor'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.category'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(related_name='actor_movies', to='movie_app.actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.ManyToManyField(related_name='country_movies', to='movie_app.country'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(related_name='director_movies', to='movie_app.director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='movies', to='movie_app.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre_en',
            field=models.ManyToManyField(null=True, related_name='movies', to='movie_app.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre_ru',
            field=models.ManyToManyField(null=True, related_name='movies', to='movie_app.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='movieframe',
            name='image',
            field=models.ImageField(upload_to='movie_moments/'),
        ),
        migrations.AlterField(
            model_name='movieframe',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='movie_app.movie'),
        ),
        migrations.AlterField(
            model_name='movievideo',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='movie_app.movie'),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movie_app.movie'),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True),
        ),
    ]
